/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mafiagame.Gui;

import mafiagame.Logic.Controller;

/**
 *
 * @author pellecarlsen
 */
public class MainGui extends javax.swing.JFrame {
Controller control;
    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
        control = new Controller();
        
        jTabbedPane.removeAll();
        jTabbedPane.add("START", start);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        start = new javax.swing.JPanel();
        startGamejButton = new javax.swing.JButton();
        highScorejButton = new javax.swing.JButton();
        pictureMafia = new javax.swing.JLabel();
        world = new javax.swing.JPanel();
        denmarkjButton = new javax.swing.JButton();
        columbiajButton = new javax.swing.JButton();
        germanyjButton = new javax.swing.JButton();
        francejButton1 = new javax.swing.JButton();
        usajButton = new javax.swing.JButton();
        afganistanjButton = new javax.swing.JButton();
        denmarkjLabel = new javax.swing.JLabel();
        columbiajLabel = new javax.swing.JLabel();
        germanyjLabel = new javax.swing.JLabel();
        francejLabel = new javax.swing.JLabel();
        usajLabel = new javax.swing.JLabel();
        afganistanjLabel = new javax.swing.JLabel();
        pictureWorld = new javax.swing.JLabel();
        denmark = new javax.swing.JPanel();
        toWorldDenmark = new javax.swing.JButton();
        pictureDenmark = new javax.swing.JLabel();
        columbia = new javax.swing.JPanel();
        toWorldColumbia = new javax.swing.JButton();
        pictureColumbia = new javax.swing.JLabel();
        germany = new javax.swing.JPanel();
        toWorldGermany = new javax.swing.JButton();
        pictureGermany = new javax.swing.JLabel();
        france = new javax.swing.JPanel();
        toWorldFrance = new javax.swing.JButton();
        pictureFrance = new javax.swing.JLabel();
        usa = new javax.swing.JPanel();
        toWorldUSA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        afghanistan = new javax.swing.JPanel();
        toWorldAfghanistan = new javax.swing.JButton();
        pictureAfghanistan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(620, 675));

        start.setLayout(null);

        startGamejButton.setText("Start Game");
        startGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGamejButtonActionPerformed(evt);
            }
        });
        start.add(startGamejButton);
        startGamejButton.setBounds(250, 450, 130, 25);

        highScorejButton.setText("High Score");
        highScorejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScorejButtonActionPerformed(evt);
            }
        });
        start.add(highScorejButton);
        highScorejButton.setBounds(250, 490, 130, 25);

        pictureMafia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/mobster-drawing2.jpg"))); // NOI18N
        start.add(pictureMafia);
        pictureMafia.setBounds(1, -4, 610, 610);

        jTabbedPane.addTab("START", start);

        world.setLayout(null);

        denmarkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denmarkjButtonActionPerformed(evt);
            }
        });
        world.add(denmarkjButton);
        denmarkjButton.setBounds(410, 120, 20, 20);

        columbiajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columbiajButtonActionPerformed(evt);
            }
        });
        world.add(columbiajButton);
        columbiajButton.setBounds(150, 320, 20, 20);

        germanyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanyjButtonActionPerformed(evt);
            }
        });
        world.add(germanyjButton);
        germanyjButton.setBounds(420, 150, 20, 20);

        francejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                francejButton1ActionPerformed(evt);
            }
        });
        world.add(francejButton1);
        francejButton1.setBounds(390, 150, 20, 20);

        usajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usajButtonActionPerformed(evt);
            }
        });
        world.add(usajButton);
        usajButton.setBounds(100, 170, 20, 20);

        afganistanjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afganistanjButtonActionPerformed(evt);
            }
        });
        world.add(afganistanjButton);
        afganistanjButton.setBounds(510, 220, 20, 20);

        denmarkjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        denmarkjLabel.setText("Denmark");
        world.add(denmarkjLabel);
        denmarkjLabel.setBounds(380, 100, 90, 22);

        columbiajLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        columbiajLabel.setText("Columbia");
        world.add(columbiajLabel);
        columbiajLabel.setBounds(110, 300, 90, 22);

        germanyjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        germanyjLabel.setText("Germany");
        world.add(germanyjLabel);
        germanyjLabel.setBounds(400, 170, 100, 22);

        francejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        francejLabel.setText("France");
        world.add(francejLabel);
        francejLabel.setBounds(310, 150, 70, 22);

        usajLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usajLabel.setText("USA");
        world.add(usajLabel);
        usajLabel.setBounds(90, 150, 36, 22);

        afganistanjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        afganistanjLabel.setText("afghanistan");
        world.add(afganistanjLabel);
        afganistanjLabel.setBounds(460, 240, 120, 22);

        pictureWorld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/world.jpg"))); // NOI18N
        world.add(pictureWorld);
        pictureWorld.setBounds(1, -4, 610, 610);

        jTabbedPane.addTab("WORLD", world);

        denmark.setLayout(null);

        toWorldDenmark.setText("To World");
        toWorldDenmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldDenmarkActionPerformed(evt);
            }
        });
        denmark.add(toWorldDenmark);
        toWorldDenmark.setBounds(500, 570, 90, 25);

        pictureDenmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/denmark.png"))); // NOI18N
        denmark.add(pictureDenmark);
        pictureDenmark.setBounds(0, 0, 610, 600);

        jTabbedPane.addTab("DENMARK", denmark);

        columbia.setLayout(null);

        toWorldColumbia.setText("To World");
        toWorldColumbia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldColumbiaActionPerformed(evt);
            }
        });
        columbia.add(toWorldColumbia);
        toWorldColumbia.setBounds(500, 570, 90, 25);

        pictureColumbia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/Colombia.jpg"))); // NOI18N
        pictureColumbia.setText("jLabel3");
        columbia.add(pictureColumbia);
        pictureColumbia.setBounds(0, 0, 610, 600);

        jTabbedPane.addTab("COLUMBIA", columbia);

        germany.setLayout(null);

        toWorldGermany.setText("To World");
        toWorldGermany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldGermanyActionPerformed(evt);
            }
        });
        germany.add(toWorldGermany);
        toWorldGermany.setBounds(500, 570, 90, 25);

        pictureGermany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/germany-distance-map.gif"))); // NOI18N
        germany.add(pictureGermany);
        pictureGermany.setBounds(0, 0, 600, 600);

        jTabbedPane.addTab("GERMANY", germany);

        france.setLayout(null);

        toWorldFrance.setText("To World");
        toWorldFrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldFranceActionPerformed(evt);
            }
        });
        france.add(toWorldFrance);
        toWorldFrance.setBounds(500, 570, 90, 25);

        pictureFrance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/france.jpg"))); // NOI18N
        france.add(pictureFrance);
        pictureFrance.setBounds(0, 0, 600, 600);

        jTabbedPane.addTab("FRANCE", france);

        usa.setLayout(null);

        toWorldUSA.setText("To World");
        toWorldUSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldUSAActionPerformed(evt);
            }
        });
        usa.add(toWorldUSA);
        toWorldUSA.setBounds(500, 570, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/usa.jpg"))); // NOI18N
        usa.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        jTabbedPane.addTab("USA", usa);

        afghanistan.setLayout(null);

        toWorldAfghanistan.setText("To World");
        toWorldAfghanistan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toWorldAfghanistanActionPerformed(evt);
            }
        });
        afghanistan.add(toWorldAfghanistan);
        toWorldAfghanistan.setBounds(510, 570, 90, 25);

        pictureAfghanistan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/800px-Afghanistan_locator_map.svg.png"))); // NOI18N
        afghanistan.add(pictureAfghanistan);
        pictureAfghanistan.setBounds(0, 0, 600, 600);

        jTabbedPane.addTab("AFGHANISTAN", afghanistan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void highScorejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScorejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScorejButtonActionPerformed

    private void startGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGamejButtonActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("DENMARK", denmark);
    }//GEN-LAST:event_startGamejButtonActionPerformed

    private void denmarkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denmarkjButtonActionPerformed
        control.setCurrentCountry("Denmark");
        jTabbedPane.removeAll();
        jTabbedPane.add("DENMARK", denmark);
    }//GEN-LAST:event_denmarkjButtonActionPerformed

    private void germanyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanyjButtonActionPerformed
        control.setCurrentCountry("Germany");
        jTabbedPane.removeAll();
        jTabbedPane.add("GERMANY", germany);
    }//GEN-LAST:event_germanyjButtonActionPerformed

    private void francejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_francejButton1ActionPerformed
        control.setCurrentCountry("France");
        jTabbedPane.removeAll();
        jTabbedPane.add("FRANCE", france);
    }//GEN-LAST:event_francejButton1ActionPerformed

    private void afganistanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afganistanjButtonActionPerformed
        control.setCurrentCountry("Afghanistan");
        jTabbedPane.removeAll();
        jTabbedPane.add("AFGHANISTAN", afghanistan);
    }//GEN-LAST:event_afganistanjButtonActionPerformed

    private void usajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usajButtonActionPerformed
        control.setCurrentCountry("USA");
        jTabbedPane.removeAll();
        jTabbedPane.add("USA", usa);
    }//GEN-LAST:event_usajButtonActionPerformed

    private void columbiajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columbiajButtonActionPerformed
        control.setCurrentCountry("Columbia");
        jTabbedPane.removeAll();
        jTabbedPane.add("COLUMBIA", columbia);
    }//GEN-LAST:event_columbiajButtonActionPerformed

    private void toWorldDenmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldDenmarkActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldDenmarkActionPerformed

    private void toWorldColumbiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldColumbiaActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldColumbiaActionPerformed

    private void toWorldGermanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldGermanyActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldGermanyActionPerformed

    private void toWorldFranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldFranceActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldFranceActionPerformed

    private void toWorldUSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldUSAActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldUSAActionPerformed

    private void toWorldAfghanistanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toWorldAfghanistanActionPerformed
        jTabbedPane.removeAll();
        jTabbedPane.add("WORLD", world);
    }//GEN-LAST:event_toWorldAfghanistanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afganistanjButton;
    private javax.swing.JLabel afganistanjLabel;
    private javax.swing.JPanel afghanistan;
    private javax.swing.JPanel columbia;
    private javax.swing.JButton columbiajButton;
    private javax.swing.JLabel columbiajLabel;
    private javax.swing.JPanel denmark;
    private javax.swing.JButton denmarkjButton;
    private javax.swing.JLabel denmarkjLabel;
    private javax.swing.JPanel france;
    private javax.swing.JButton francejButton1;
    private javax.swing.JLabel francejLabel;
    private javax.swing.JPanel germany;
    private javax.swing.JButton germanyjButton;
    private javax.swing.JLabel germanyjLabel;
    private javax.swing.JButton highScorejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel pictureAfghanistan;
    private javax.swing.JLabel pictureColumbia;
    private javax.swing.JLabel pictureDenmark;
    private javax.swing.JLabel pictureFrance;
    private javax.swing.JLabel pictureGermany;
    private javax.swing.JLabel pictureMafia;
    private javax.swing.JLabel pictureWorld;
    private javax.swing.JPanel start;
    private javax.swing.JButton startGamejButton;
    private javax.swing.JButton toWorldAfghanistan;
    private javax.swing.JButton toWorldColumbia;
    private javax.swing.JButton toWorldDenmark;
    private javax.swing.JButton toWorldFrance;
    private javax.swing.JButton toWorldGermany;
    private javax.swing.JButton toWorldUSA;
    private javax.swing.JPanel usa;
    private javax.swing.JButton usajButton;
    private javax.swing.JLabel usajLabel;
    private javax.swing.JPanel world;
    // End of variables declaration//GEN-END:variables
}
