/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mafiagame.Gui;

/**
 *
 * @author Ebbe
 */
public class World extends javax.swing.JPanel {

    /**
     * Creates new form World
     */
    public World() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColumbiaButton = new javax.swing.JButton();
        DenmarkButton = new javax.swing.JButton();
        ColumbiaLabel = new javax.swing.JLabel();
        DenmarkLabel = new javax.swing.JLabel();
        worldPicture = new javax.swing.JLabel();

        setLayout(null);
        add(ColumbiaButton);
        ColumbiaButton.setBounds(150, 310, 20, 20);

        DenmarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenmarkButtonActionPerformed(evt);
            }
        });
        add(DenmarkButton);
        DenmarkButton.setBounds(410, 120, 20, 20);

        ColumbiaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ColumbiaLabel.setText("Columbia");
        add(ColumbiaLabel);
        ColumbiaLabel.setBounds(120, 290, 90, 22);

        DenmarkLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DenmarkLabel.setText("Denmark");
        add(DenmarkLabel);
        DenmarkLabel.setBounds(380, 100, 100, 22);

        worldPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiagame/pictures/world.jpg"))); // NOI18N
        add(worldPicture);
        worldPicture.setBounds(0, 0, 600, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void DenmarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenmarkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenmarkButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColumbiaButton;
    private javax.swing.JLabel ColumbiaLabel;
    private javax.swing.JButton DenmarkButton;
    private javax.swing.JLabel DenmarkLabel;
    private javax.swing.JLabel worldPicture;
    // End of variables declaration//GEN-END:variables
}
